#cloud-config

# Send pre-generated ssh private keys to the server
# If these are present, they will be written to /etc/ssh and
# new random keys will not be generated
#  in addition to 'rsa' and 'dsa' as shown below, 'ecdsa' is also supported

ssh_keys:
  rsa_private: ${bastion_private_key}

  rsa_public: ${bastion_public_key}
